window.PORTFOLIO_PROJECTS = [
  {
    title: "ACE",
    description: "BI · Personal Branding",
    image: "assets/works/ace.png",
    imageAlt: "ACE project preview",
    href: "ace/",
    nodeId: "288:458",
  },
  {
    title: "Brand New Day",
    description: "UX/UI· Promotional Web",
    image: "assets/works/brand-new-day.jpg",
    imageAlt: "Brand New Day project preview",
    href: "brand-new-day/",
    nodeId: "288:459",
  },
  {
    title: "Calmato",
    description: "UX/UI· Responsive Web",
    image: "assets/works/calmato.png",
    imageAlt: "Calmato project preview",
    href: "calmato",
    nodeId: "288:460",
  },
  {
    title: "Youtube Calmato",
    description: "Youtube",
    image: "assets/works/youtube-calmato.png",
    imageAlt: "Youtube Calmato project preview",
    href: "https://youtube.com/channel/UCyv16-9W5sOhQr-svxCJ1qQ?si=epe7wnfn21DEp5SN",
    external: true,
    nodeId: "288:461",
  },
  {
    title: "Beerby",
    description: "UX/UI· Mobile App Design",
    image: "assets/works/beerby.jpg",
    imageAlt: "Beerby project preview",
    href: "Beerby",
    nodeId: "288:462",
  },
  {
    title: "On The Trip",
    description: "UX/UI· Mobile App Design",
    image: "assets/works/on-the-trip.png",
    imageAlt: "On The Trip project preview",
    href: "On The Trip",
    nodeId: "288:463",
  },
  {
    title: "Zippo",
    description: "UX/UI· Responsive Web",
    image: "assets/works/zippo.jpg",
    imageAlt: "Zippo project preview",
    href: "#visual",
    nodeId: "288:464",
  },
  {
    title: "철거병단",
    description: "UX/UI· Responsive Web",
    image: "assets/works/demolition-corps.png",
    imageAlt: "철거병단 project preview",
    href: "#visual",
    nodeId: "288:465",
  },
];
